TITLE INDIRECT ADDRESSING
INCLUDE IRVINE32.INC

.DATA
ARRAY		WORD	23H, 45H, 45H, 56H, 25H, 44H, 22H, 54H, 12H
CONSTVAL	WORD	20H
MODARRAY	WORD	9	DUP(?)

.CODE
MAIN PROC

MOV ECX, LENGTHOF ARRAY; INITALIZE LOOP
MOV ESI, 0
L1:
MOV AX, ARRAY[ESI]
ADD AX, CONSTVAL
MOV [MODARRAY+ESI], AX
ADD ESI, TYPE ARRAY
LOOP L1

MOV EBX, OFFSET MODARRAY
MOV ECX, LENGTHOF MODARRAY; INITALIZE LOOP
MOV ESI, 0

L2:
MOV EAX, [EBX+ESI]
CALL WRITEHEX
CALL CRLF
ADD ESI, TYPE MODARRAY
LOOP L2
EXIT
MAIN ENDP
END MAIN